name: Build Chromium for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo @echo off > set_path.bat
        echo set DEPOT_TOOLS_WIN_TOOLCHAIN=0 >> set_path.bat
        echo set PATH=%CD%\depot_tools;%PATH% >> set_path.bat
        call set_path.bat
        gclient

    - name: Fetch Chromium source code
      run: |
        mkdir chromium
        cd chromium
        fetch --nohooks --no-history chromium

    - name: Install Chromium build dependencies
      run: |
        cd chromium/src
        build/install-build-deps-win.bat

    - name: Generate build files
      run: |
        cd chromium/src
        gn gen out/Default --args="is_debug=false is_official_build=true symbol_level=0 enable_nacl=false"

    - name: Build Chromium
      run: |
        cd chromium/src
        ninja -C out/Default chrome

    - name: Upload Chromium build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: chromium-build
        path: chromium/src/out/Default/
