name: Build Chromium

on: [workflow_dispatch]

jobs:
  build:
    name: Build Chromium
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        # Install additional dependencies required by Chromium, adjust as needed

    - name: Configure Chromium build
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH="$PATH:${PWD}/depot_tools"
        mkdir chromium && cd chromium
        fetch --nohooks --no-history chromium
        cd src
        ./build/install-build-deps.sh

    - name: Build Chromium
      run: |
        cd chromium/src
        gn gen out/Default
        ninja -C out/Default chrome

    - name: Archive Chromium build
      uses: actions/upload-artifact@v2
      with:
        name: chromium-build
        path: chromium/src/out/Default/
